services:
  app:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - "${APP_PORT:-8000}:8000" # Use APP_PORT from .env, default to 8000 if not set
    depends_on:
      - db
    networks:
      - simple-pro
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - simple-pro
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data    
    networks:
      - simple-pro

volumes:
  postgres_data:
networks:
  simple-pro:
    driver: bridge